### ISSUE TITLE
Question: Does this work for custom baud on linux sytem?

### ISSUE THREAD

**Issue by soypat** [charles-d-burton/serinit#1]
@charles-d-burton  I have a device with faulty clock. It's "9600" baud is actually closer to 9700. This causes errors when reading on linux. Windows does allow for custom bauds

**Comment by charles-d-burton** [comment]
It should.  Give me a couple of hours, I'm away from my computer right now, and I'll add a function to set a custom baud rate.

**Comment by charles-d-burton** [comment]
@soypat I ran into some work stuff.  I'm working up some updates to it so that it's more versatile.  Meaning I'm building it so that it has an options block that also sets sane defaults.  That way you're not forced to use the autodiscovery feature and can instead specify what you want including the baud rate.  This should work fine for weird baud rates as well.

**Comment by charles-d-burton** [comment]
@soypat It should be updated with a New function you can use like this:
```go
device, err := serinit.New(&serinit.Options{
  Baud: 9690,
  DataBits: 8,
  TTY: "/dev/serial/ACM0", //or whatever your device is
})
```

**Comment by charles-d-burton** [comment]
It's untested though, I don't really have a device handy I can test it with

**Comment by soypat** [comment]
I'll test it one of these days. Thanks a bunch!

**Comment by soypat** [comment]
I ended up using sers directly to open the port as it was more straightforward. Thanks for the quick help though!

**Comment by charles-d-burton** [comment]
NP, I really designed this so that it could connect to and control a farm of 3D printers so it wasn't really intended for more general use.
